#pragma once
// config.h — 联调固件配置
// 本地新建 config.local.h 覆盖 WiFi / 基站 IP（勿提交密钥）

#if __has_include("config.local.h")
#include "config.local.h"
#endif

#ifndef MERGETEST_WIFI_SSID
#define MERGETEST_WIFI_SSID "YOUR_WIFI_SSID"
#endif
#ifndef MERGETEST_WIFI_PASSWORD
#define MERGETEST_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#endif

#ifndef MERGETEST_BASE_STATION_IP
#define MERGETEST_BASE_STATION_IP "192.168.1.100"
#endif
#ifndef MERGETEST_BASE_STATION_PORT
#define MERGETEST_BASE_STATION_PORT 8765
#endif

#ifndef OTA_HOSTNAME
#define OTA_HOSTNAME "xiao-an-esp32"
#endif
#ifndef OTA_PASSWORD
#define OTA_PASSWORD ""
#endif

// 设备身份（发给基站同学）
#ifndef MERGETEST_DEVICE_ID
#define MERGETEST_DEVICE_ID "xiaoan_robot_01"
#endif
#ifndef MERGETEST_FIRMWARE_VERSION
#define MERGETEST_FIRMWARE_VERSION "robot-fw-0.1"
#endif
#ifndef MERGETEST_DEVICE_ROLE
#define MERGETEST_DEVICE_ROLE "robot"
#endif

// 心跳间隔 ms（联调阶段 2s，与 docs 正式版 10s 不同）
#ifndef MERGETEST_HEARTBEAT_MS
#define MERGETEST_HEARTBEAT_MS 2000
#endif

// 视频：联调默认 1 fps；分辨率与 MERGETEST_CAMERA_USE_VGA 对齐（协议目标 640×480）
#ifndef MERGETEST_VIDEO_BASE64_FALLBACK
#define MERGETEST_VIDEO_BASE64_FALLBACK 0
#endif
#ifndef MERGETEST_VIDEO_INTERVAL_MS
#define MERGETEST_VIDEO_INTERVAL_MS 1000
#endif
#ifndef MERGETEST_CAMERA_USE_VGA
#define MERGETEST_CAMERA_USE_VGA 1
#endif
#ifndef MERGETEST_CAMERA_JPEG_QUALITY
#define MERGETEST_CAMERA_JPEG_QUALITY (MERGETEST_CAMERA_USE_VGA ? 10 : 12)
#endif
#ifndef MERGETEST_CAMERA_FB_COUNT
#define MERGETEST_CAMERA_FB_COUNT 2
#endif
#if MERGETEST_CAMERA_USE_VGA
#ifndef MERGETEST_VIDEO_WIDTH
#define MERGETEST_VIDEO_WIDTH 640
#endif
#ifndef MERGETEST_VIDEO_HEIGHT
#define MERGETEST_VIDEO_HEIGHT 480
#endif
#else
#ifndef MERGETEST_VIDEO_WIDTH
#define MERGETEST_VIDEO_WIDTH 320
#endif
#ifndef MERGETEST_VIDEO_HEIGHT
#define MERGETEST_VIDEO_HEIGHT 240
#endif
#endif

#ifndef MERGETEST_ENABLE_MIC
#define MERGETEST_ENABLE_MIC 0
#endif

// 0 = 128x160 ST7735 (display.cpp)  1 = 2.4" ST7789 face240（face240_display.cpp）
#ifndef MERGETEST_DISPLAY_FACE240
#define MERGETEST_DISPLAY_FACE240 0
#endif
// 硬件开关（相机与 TFT 引脚冲突，同机只能开一个）
#ifndef MERGETEST_ENABLE_DISPLAY
#define MERGETEST_ENABLE_DISPLAY 1
#endif
#ifndef MERGETEST_ENABLE_CAMERA
#define MERGETEST_ENABLE_CAMERA 1
#endif
#ifndef MERGETEST_ENABLE_SPEAKER
#define MERGETEST_ENABLE_SPEAKER 1
#endif
#ifndef MERGETEST_ENABLE_MOTOR
#define MERGETEST_ENABLE_MOTOR 1
#endif

// 串口 mock ASR：输入行 mock:文本 会发 asr.transcript.mock
#ifndef MERGETEST_ENABLE_SERIAL_MOCK_ASR
#define MERGETEST_ENABLE_SERIAL_MOCK_ASR 1
#endif

// I2S 扬声器引脚（MAX98357A）
#ifndef MERGETEST_SPEAKER_BCLK
#define MERGETEST_SPEAKER_BCLK 39
#endif
#ifndef MERGETEST_SPEAKER_LRC
#define MERGETEST_SPEAKER_LRC 40
#endif
#ifndef MERGETEST_SPEAKER_DIN
#define MERGETEST_SPEAKER_DIN 47
#endif
#ifndef MERGETEST_SPEAKER_SAMPLE_RATE
#define MERGETEST_SPEAKER_SAMPLE_RATE 16000
#endif
