#!/usr/bin/env python3
"""Generate machine-readable file inventories for docs/agents/_generated/.

Run from repo root:
    python tools/generate_agent_registry.py

Does NOT overwrite human-written status in 02_*.md — only file lists + git hints.
"""

from __future__ import annotations

import re
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "agents" / "_generated"


def git_lines(*args: str) -> str:
    try:
        r = subprocess.run(
            ["git", "-C", str(ROOT), *args],
            capture_output=True,
            text=True,
            check=False,
        )
        return r.stdout.strip() or "(no output)"
    except OSError:
        return "(git unavailable)"


def list_source_files(base: Path, patterns: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for pat in patterns:
        files.extend(sorted(base.rglob(pat)))
    return sorted(set(files))


def parse_platformio_envs(ini_path: Path) -> list[str]:
    if not ini_path.exists():
        return []
    text = ini_path.read_text(encoding="utf-8")
    return re.findall(r"^\[env:([^\]]+)\]", text, re.MULTILINE)


def md_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def write_inventory() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()

    fw_src = ROOT / "robot" / "firmware" / "src"
    merge_src = ROOT / "robot" / "mergetesting" / "src"
    fw_envs = parse_platformio_envs(ROOT / "robot" / "firmware" / "platformio.ini")
    merge_envs = parse_platformio_envs(ROOT / "robot" / "mergetesting" / "platformio.ini")

    fw_files = list_source_files(fw_src, ("*.cpp", "*.h"))
    merge_files = list_source_files(merge_src, ("*.cpp", "*.h")) if merge_src.exists() else []

    fw_rows = [[f"`{f.name}`", str(f.relative_to(ROOT)), str(f.stat().st_size)] for f in fw_files]
    merge_rows = [[f"`{f.name}`", str(f.relative_to(ROOT)), str(f.stat().st_size)] for f in merge_files]

    py_tests = sorted((ROOT / "tests").rglob("test_*.py"))
    test_rows = [[str(p.relative_to(ROOT)), str(p.stat().st_size)] for p in py_tests]

    content = f"""# Auto-generated inventory — {today}

> Generated by `tools/generate_agent_registry.py`. Do not hand-edit.

## Git shortlog (last 5 commits, firmware)

```
{git_lines("log", "-5", "--oneline", "--", "robot/firmware/", "robot/mergetesting/", "base_station/", "agent/")}
```

## Git diff stat (uncommitted)

```
{git_lines("diff", "--stat")}
```

## robot/firmware/src ({len(fw_files)} files)

{md_table(["文件", "路径", "字节"], fw_rows)}

## PlatformIO envs — robot/firmware ({len(fw_envs)})

{", ".join(f"`{e}`" for e in fw_envs)}

## robot/mergetesting/src ({len(merge_files)} files)

{md_table(["文件", "路径", "字节"], merge_rows) if merge_rows else "_目录不存在或为空_"}

## PlatformIO envs — mergetesting ({len(merge_envs)})

{", ".join(f"`{e}`" for e in merge_envs) if merge_envs else "—"}

## tests/**/test_*.py ({len(py_tests)} files)

{md_table(["路径", "字节"], test_rows)}
"""
    (OUT_DIR / "file_inventory.md").write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_DIR / 'file_inventory.md'}")


if __name__ == "__main__":
    write_inventory()
