[env:esp32-s3-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    espressif/esp32-camera@^2.0.0
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
